highlighter/highlighter/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect



urlpatterns = [
    url(r'^$', lambda r:redirect('home:project_list'), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^homee/',include('home.urls',namespace='home')),
    url(r'^study/',include('study.urls',namespace='study')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/',include(debug_toolbar.urls)),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

highlighter/home/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^new/$',views.project_new,name="project_new"),
    url(r'^(?P<id>\d+)/edit/$',views.project_edit),
    url(r'^search/$',views.project_search, name='project_search'),
    url(r'^$',views.project_list, name='project_list'),
    url(r'^(?P<id>\d+)/$',views.project_detail, name='project_detail'),
    url(r'^(?P<id>\d+)/like$',views.project_like, name='project_like'),
    url(r'^rcmd/$',views.project_rcmd, name='project_rcmd'),
]

highlighter/home/models.py
from django.db import models
from django.conf import settings
from django import forms
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from django.urls import reverse
from study.models import Study


def min_length_3_validator(value):
    if len(value) < 3:
        raise forms.ValidationError('3글자이상입력하세요')
    pass

class Project(models.Model):

    STATUS_CHOICES = (
        ('d','Draft'),
        ('p', 'Published'),
    )

    #user = models.ForeignKey(settings.AUTH_USER_MODEL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100, verbose_name='제목',validators=[min_length_3_validator])

    body = models.TextField(verbose_name='내용',default=".")
    photo = models.ImageField(blank=True, upload_to='home/project/%Y/%m/%d')
    # photo_thumbnail = ImageSpecField(source='photo', processors=[Thumbnail(300, 300)], format='JPEG',
    #                                         options={'quality', 60})
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="Draft")
    like = models.IntegerField(blank=True, default=0)
    tag_set = models.ManyToManyField('Tag',blank=True)
    #태그는솔찍히빈칸이여도됨
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    type = models.ForeignKey(Study,blank=True, null=True)

    def __str__(self):
        return self.title



class Comment(models.Model):
    project = models.ForeignKey(Project)
    author = models.CharField(max_length=20)
    message = models.TextField() 
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message

class Todo(models.Model):
    project = models.ForeignKey(Project)
    todo= models.CharField(max_length=20)
    completed= models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.todo

class Tag(models.Model):
    name = models.CharField(max_length=50,unique=True) #태그는중복되면안되니깐
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    read = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    updated_date = models.DateTimeField(auto_now_add=False, auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True, auto_now=False)

highlighter/home/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.Form):
    # class Meta:
    #     model = Project
    #
    #     fields = '__all__'
    #


    title = forms.CharField()
    body = forms.CharField(widget=forms.Textarea)



    # def save(self,commit):
    #     project = Project()
    #
    #     # project.user_id = '1'
    #     # 딕셔너리
    #     # project.title = form.cleaned_data['title']
    #     # project.content= form.cleaned_data['content']
    #     project = Project(**self.cleaned_data)  # 이방식쓸려면modelform써야됨
    #     if commit:
    #         project.save()
    #         return project

highlighter/home/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import get_object_or_404,render,redirect
from .models import Project
from accounts.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from .forms import ProjectForm
# Create your views here.
import math, random
from collections import defaultdict, Counter

import json
from django.http import HttpResponse
from haystack.query import SearchQuerySet

from random import sample, randint


def project_new(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        project = Project()

        login_user = request.user
        user = get_object_or_404(User, username=login_user)

        if form.is_valid():
            project.user_id = user.id
            project.title = form.cleaned_data['title']

            #             project.body = form.cleaned_data['body']
            #             project.status= "p"
            #             project.like= 0
            # #            project.type = study
            #             project.save()
            #             messages.success(request, ' 새 포스팅을 저장했습니다')
            return redirect('/homee/')


    else:
        form = ProjectForm()

    return render(request,'homee/project_form.html',{
        'form':form,
    })

def project_edit(request, id):
    project = get_object_or_404(Project, id=id)
    if request.method == 'POST':
        form = ProjectForm(request.POST,request.FILES, instance=project) #project_new에인스턴스추가만하면 수정기능 끝
        if form.is_valid():#모든validate호출하기
            project = Project()
            project = form.save()

            return redirect('/homee/')
        else:
            form.errors

    else:
        form = ProjectForm(instance=project) #project_new에인스턴스추가만하면 수정기능 끝
        #처음에열릴때

    return render(request,'homee/project_form.html',{
        'form': form,
    })

def project_list(request):
    qs = Project.objects.all()


    # a = request.GET.get('a','')
    #
    # if a:
    #     qs = qs.filter(title__icontains=a)
    #     print(qs)


    return render(request, 'homee/project_list.html', {
        'project_list':qs,
        # 'q':a,
    })





def project_detail(request,id):
    # try:
    #     project = Project.objects.get(id=id)
    # except Project.DoesNotExist:
    #     raise  Http404

    project = get_object_or_404(Project, id=id)
    return render(request, 'homee/project_detail.html', {
        'project' : project
    })



u_dict = {}
def project_like(request,id):

    project = get_object_or_404(Project, id=id)
    login_user = request.user
    user = get_object_or_404(User,username=login_user)
    profile = get_object_or_404(Profile,user_id=user.id)

    if login_user in u_dict and project.id in u_dict[login_user]:
        #print("login_usr: {}, project.id: {}",format(login_user),format(project.id))
        pass
    else:
        project.like += 1
        project.save()
        if login_user in u_dict:
            global dict
            u_dict[login_user].add(project.id)
        else:
            u_dict[login_user] = set()
            u_dict[login_user].add(project.id)

        print(u_dict)


        profile.array_rated_project_indexs += (str(project.id)+',')
        profile.save()

    return redirect('/homee/'+id)

def project_rcmd_u(request):
    login_user = request.user

    user = get_object_or_404(User, username=login_user)
    # print('login_user', login_user)
    # print('user.id', user.id)
    profile = get_object_or_404(Profile, user_id=user.id)
    login_user_rated_list_field = profile.array_rated_project_indexs
    users = User.objects.all()
    all_profile = Profile.objects.all()
    login_user_rated_list = login_user_rated_list_field.split(',')[0:-1]
    # print(login_user_rated_list)
    users_interests = []
    login_user_id = None

    print('profile.id', profile.id)

    for user in users:
        print('user', user)
        # print(user.id,user) # FIXME: user and profile is important
        profile = get_object_or_404(Profile, user_id=user.id)
        print('profile', profile.id)
        users_profile_rated = profile.array_rated_project_indexs.split(',')[0:-1]
        users_interests.append(users_profile_rated)

    # important! re call user & profile cuz import reason
    user = get_object_or_404(User, username=login_user)
    profile = get_object_or_404(Profile, user_id=user.id)
    print('profile.id', profile.id)
    id_list = [t.id for t in all_profile]

    print('profile.id', profile.id)
    print('id+list', id_list)

    for t in range(len(id_list)):
        print('profile.id', profile.id)
        print('id_list[{}]', {t}, id_list[t])
        if id_list[t] == profile.id:
            login_user_id = t
            print('login_user_id', login_user_id)

    def dot(v, w):
        return sum(v_i * w_i for v_i, w_i in zip(v, w))

    def cosine_similarity(v, w):
        return dot(v, w) / math.sqrt(dot(v, v) * dot(w, w))

    unique_interests = sorted(list({interest
                                    for user_interests in users_interests
                                    for interest in user_interests}))

    print("user_interests", users_interests)
    print("unique_interests", unique_interests)

    def make_user_interest_vector(user_interests):
        return [1 if interest in user_interests else 0 for interest in unique_interests]

    user_interest_matrix = list(map(make_user_interest_vector, users_interests))

    print("all_user:interest_vector:", user_interest_matrix)

    user_similarities = [[cosine_similarity(interest_vector_i, interest_vector_j)
                          for interest_vector_j in user_interest_matrix]
                         for interest_vector_i in user_interest_matrix]

    def most_similar_users_with_me(user_id):
        pairs = [(other_user_id, similarity)  # find other
                 for other_user_id, similarity in  # users with
                 enumerate(user_similarities[user_id])  # nonzero
                 if user_id != other_user_id and similarity > 0]  # similarity

        return sorted(pairs,  # sort them
                      key=lambda pair: pair[1],  # most similar
                      reverse=True)

    print("most_similar_users:", most_similar_users_with_me(0))

    def user_based_suggestions(user_id, include_current_interests=False):
        # sum up the similarities
        suggestions = defaultdict(float)

        for similar_user, similarity in most_similar_users_with_me(user_id):
            for interest in users_interests[similar_user]:
                suggestions[interest] += similarity
                print(suggestions)

        # convert them to a sorted list
        suggestions = sorted(suggestions.items(),
                             key=lambda pair: pair[1],
                             reverse=True)

        # and (maybe) exclude already-interests
        if include_current_interests:
            return suggestions
        else:
            print([(suggestion, weight)
                    for suggestion, weight in suggestions
                    if suggestion not in users_interests[user_id]][0:12])
            # return [(suggestion, weight)
            return [suggestion
                    for suggestion, weight in suggestions
                    if suggestion not in users_interests[user_id]][0:12]

    print("user_based_suggestions", user_based_suggestions(login_user_id))

    int_list = []
    for t in map(int,user_based_suggestions(login_user_id)):
        int_list.append(t)

    print(int_list)
    qs = Project.objects.filter(id__in=int_list)

    return render(request, 'homee/project_rcmd.html', {
        'project_list': qs,
        # 'indifferent': qs_not,
    })

def project_rcmd(request):
    login_user = request.user


    user = get_object_or_404(User,username=login_user)
    # print('login_user', login_user)
    # print('user.id', user.id)
    profile = get_object_or_404(Profile, user_id=user.id)
    login_user_rated_list_field = profile.array_rated_project_indexs
    users = User.objects.all()
    all_profile = Profile.objects.all()
    login_user_rated_list = login_user_rated_list_field.split(',')[0:-1]
    #print(login_user_rated_list)
    users_interests = []
    login_user_id = None

    print('profile.id', profile.id)
    # for cnt in range(len(users)):
    #     profile = get_object_or_404(Profile, user_id=users[cnt].id)
    #     users_profile_rated = profile.array_rated_project_indexs.split(',')[0:-1]
    #     print(users_profile_rated)
    #
    #     if login_user_rated_list == users_profile_rated:
    #         login_user_id = cnt
    #         # print(login_user_id)
    #         users_interests.append(users_profile_rated)
    #     else:
    #         users_interests.append(users_profile_rated)

    for user in users:
        print('user',user)
        #print(user.id,user) # FIXME: user and profile is important
        profile = get_object_or_404(Profile,user_id=user.id)
        print('profile', profile.id)
        users_profile_rated = profile.array_rated_project_indexs.split(',')[0:-1]
        users_interests.append(users_profile_rated)


    # important! re call user & profile cuz import reason
    user = get_object_or_404(User, username=login_user)
    profile = get_object_or_404(Profile, user_id=user.id)
    print('profile.id', profile.id)
    id_list = [t.id for t in all_profile]

    print('profile.id', profile.id)
    print('id+list',id_list)

    for t in range(len(id_list)):
        print('profile.id',profile.id)
        print('id_list[{}]',{t},id_list[t])
        if id_list[t] == profile.id:
            login_user_id = t
            print('login_user_id',login_user_id)





    def dot(v, w):
        return sum(v_i * w_i for v_i, w_i in zip(v, w))

    def cosine_similarity(v, w):
        return dot(v, w) / math.sqrt(dot(v, v) * dot(w, w))

highlighter/home/templates/home/project_detail.html
{%  extends "home/layout.html" %}
{%  load imagekit %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>{{ project.title }}</h1>
                {% if project.photo %}
                    {#                <img src="/media/{{ project.photo }}" style="max-width: 100%" />#}
                    <img src="{{ project.photo.url }}" style="max-width: 100%" />

                    {#                    {% thumbnail "200x100" project.photo -- style="" onclick="" class=""%}#}

                {%  endif %}

                {{ project.content|linebreaks }}
                <hr/>
                <h2>to-do리스트</h2>
                <form class="form-horizontal">
                    <div class="form-group">
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="newTodo" placeholder="할일">
                        </div>
                        <button type="button" id="addItem" class="btn btn-success">추가</button>
                    </div>
                </form>
                {{ project.content_set.all }}
                <ul id="todos">
                    {% for todo in project.todo_set.all %}
                        {#                        <li>#}
                        {#                            {{ todo.todo }}#}
                        {#                            <small> {{ todo.completed}}</small>#}
                        {#                            <small>at {{ todo.create_at}}</small>#}
                        {#                            <small>at {{ todo.updated_at }}</small>#}
                        {#                        </li>#}
                    {% endfor %}
                </ul>
                <hr/>

                <h2>댓글</h2>
                {{ project.content_set.all }}
                <ul>
                    {% for comment in project.comment_set.all %}
                        <li>
                            {{ comment.message }}
                            <small>by {{ comment.author}}</small>
                            <small>at {{ comment.updated_at }}</small>
                        </li>
                    {% endfor %}
                </ul>
                <a href="{% url "home:project_list" %}" class="btn btn-primary">글 목록</a>
                <a href="{% url "home:project_like" project.id %}" class="btn btn-primary">like!</a> <p>like:{{ project.like }}</p>
            </div>
        </div>
    </div>


{%  endblock %}

highlighter/home/templates/home/project_form.html
{% extends "home/layout.html" %}

{% block content %}

    {#    <div class="container">#}
    {#        <div class="row">#}
    {#            <div class="col-md-12">#}
    {#                <h1>Project Form</h1>#}
    {##}
    {##}
    {##}
    {#                <form action="" method="post">#}
    {#                    {% csrf_token %}#}
    {##}
    {#                    <table class="table table-hover table-bordered">#}
    {#                        {{  form.as_table }} {% comment %}에러났을때보여줌{% endcomment %}#}
    {#                    </table>#}
    {#                    <input type="submit" value="제출" class="btn btn-primary">#}
    {#                </form>#}
    {##}
    {##}
    {##}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}



    {% load bootstrap3 %}

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
{#                enctype안하면사진안올라감#}
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>


{% endblock %}

highlighter/home/templates/home/project_list.html
{% extends "home/layout.html" %}
{% load imagekit %}
{% load bootstrap3 %}
{% block content %}

    <div class="container">
        <div class="jumbotron">
            <h1>HighLighter Project <sup>by coldcrust</sup></h1>
            <p>여러분의 자기관리 페이스메이커가 되어드리겠습니다.</p>
            <h2>
                <a class="btn btn-lg btn-primary" href="{% url "home:project_rcmd" %}">
                    내 스터디 추천받기^^
                </a>
            </h2>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class ="alert alert-info">
                    <ul>
                        <li>
                            http://localhost:8000/home 주소로 접속.
                        </li>
                        <li>
                            빨리졸업하고싶다.졸업하고 편의점알바하면서 살아야지.
                        </li>
                    </ul>
                </div>

                <a href="{% url "home:project_new" %}" class="btn btn-primary pull-right">새글 쓰기</a>

                <p>
                <form action="" method="get">
                    <input type="text" name="a" value="{{ q }}" />
                    <input type="submit" value="검색" class = "btn btn-primary"/>
                </form>
                <form action="" method="get">
                    <input type="text" name="q" value="{{ fq }}" />
                    <input type="submit" value="full-text검색" class = "btn btn-primary"/>
                </form>
                </p>
                <table class="table table-hover table-bordered">

                    <tbody>


                    {% for project in project_list%}
                        <tr>
                            <div class="col-sm-6 col-md-3">
                                <div class="thumbnail">
                                    {% if project.photo %}
                                        {% thumbnail "200x100" project.photo -- style="" onclick="" class=""%}
                                    {%  endif %}
                                    <div class="caption">
                                        <a href="{% url "home:project_detail" project.id %}">
                                            {{ project.title }}
                                        </a>

                                    </div>
                                    <div class="caption">
                                        <a>{{ project.user }}</a>
                                        {{ project.created_at }}
                                    </div>

                                </div>
                            </div>

                            {#                            <td>{{ project.id }}</td>#}
                            {##}
                            {#                            <td>#}
                            {#                                {% if project.photo %}#}
                            {#                                    {% thumbnail "200x100" project.photo -- style="" onclick="" class=""%}#}
                            {#                                {%  endif %}#}
                            {#                            </td>#}
                            {##}
                            {#                            <td>#}
                            {#                                <a href="{% url "home:project_detail" project.id %}">#}
                            {#                                    {{ project.title }}#}
                            {#                                </a>#}
                            {#                            </td>#}

                            {#                <a href="/home/{{ project.id }}">#}
                            {#                    {{ project.title }}#}
                            {#                </a></li>#}
                            {#                            <td><small>{{ project.author }}</small></td>#}
                            {#                            <td><small>{{ project.updated_at}}</small></td>#}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}