highlighter/highlighter/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect



urlpatterns = [
    url(r'^$', lambda r:redirect('home:project_list'), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^homee/',include('home.urls',namespace='home')),
    url(r'^study/',include('study.urls',namespace='study')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/',include(debug_toolbar.urls)),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

highlighter/home/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^new/$',views.project_new,name="project_new"),
    url(r'^(?P<id>\d+)/edit/$',views.project_edit),
    url(r'^search/$',views.project_search, name='project_search'),
    url(r'^$',views.project_list, name='project_list'),
    url(r'^(?P<id>\d+)/$',views.project_detail, name='project_detail'),
    url(r'^(?P<id>\d+)/like$',views.project_like, name='project_like'),
    url(r'^rcmd/$',views.project_rcmd, name='project_rcmd'),
]

highlighter/study/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.study_list, name='study_list'),
    url(r'^(?P<id>\d+)/$',views.study_detail),
    url(r'^(?P<id>\d+)/participate$', views.study_participate, name='study_participate'),
    url(r'^(?P<id>\d+)/makeproject$', views.study_makeproject, name='study_makeproject'),
]

highlighter/study/models.py
from django.db import models
from django.conf import settings

class Study(models.Model):

    #id는 자동생성
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100, verbose_name='제목')
    content = models.TextField(verbose_name='설명')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_set = models.ManyToManyField('accounts.Profile', blank=True)

    def __str__(self):
        return self.title


class GroupTodo(models.Model):
    study = models.ForeignKey(Study)
    todo= models.CharField(max_length=20)
    completed= models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.todo

class Post(models.Model):

    STATUS_CHOICES = (
        ('d','Draft'),
        ('p', 'Published'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    study = models.ForeignKey(Study)
    title = models.CharField(max_length=100, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

highlighter/study/forms.py
# study/forms.py

from django import forms

class ProjectForm(forms.Form):
    # user =forms.
    #     models.ForeignKey(settings.AUTH_USER_MODEL)
    title = forms.CharField()
    body = forms.CharField(widget=forms.Textarea)

highlighter/study/views.py
from django.shortcuts import redirect, render
from django.shortcuts import get_object_or_404,render
from .models import Study
from accounts.models import Profile
from accounts.models import User
from .forms import ProjectForm
from home.models import Project

# Create your views here.

def study_list(request):
    qs = Study.objects.all()
    q = request.GET.get('q','')
    if q:
        qs = qs.filter(title__icontains=q)

    return render(request, 'study/study_list.html', {
        'study_list':qs,
        'q':q,
    })


def study_detail(request,id):
    study = get_object_or_404(Study, id=id)
    # I'm not sure why .filter but just .get() is schema design error
    # https://stackoverflow.com/questions/22063748/django-get-returned-more-than-one-topic
    project = Project.objects.filter(type=id)


    return render(request, 'study/study_detail.html', {
        'study' : study,
        'project' : project,
    })


def study_participate(request,id):
    study = get_object_or_404(Study, id=id)
    login_user = request.user
    user = get_object_or_404(User, username=login_user)
    profile= get_object_or_404(Profile, user_id=user.id)
    study.user_set.add(profile.id)
    study.save()

    return render(request, 'study/study_detail.html', {
        'study' : study
    })


def study_makeproject(request,id):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        project = Project()

        login_user = request.user
        user = get_object_or_404(User, username=login_user)

        study = get_object_or_404(Study, id=id)

        if form.is_valid():
            project.user_id = user.id
            project.title = form.cleaned_data['title']

            project.body = form.cleaned_data['body']
            project.status= "p"
            project.like= 0
            project.type = study
            project.save()
            return redirect('/study/')



    else:
        form = ProjectForm()
    return render(request,'study/study_makeproject.html',{
        'form':form,
    })

highlighter/study/templates/study/study_detail.html
{%  extends "homee/layout.html" %}
{%  load imagekit %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <h1>{{ study.title }}</h1>

                <div class="container">
                    <div class="col-md-4"><h5>참여자: {% for t in study.user_set.all%}{{ t }} {% endfor %}</h5></div>
                    <div class="col-md-4 col-md-offset-4"> <h5>스터디장: {{ study.user}}</h5></div>
                    <div class="col-md-4">{{ study.created_at }}</div>
                    <div class="col-md-4 col-md-offset-4"><a href="{% url "study:study_participate" study.id %}" class="btn btn-primary btn-lg">Part-In!</a></div>
                </div>
                <hr>
                {{ study.content|linebreaks }}
                <hr/>
                <h4>참여자</h4>


                <div class="row sizess">
                    {% for i in study.user_set.all%}
                        <div class="col-xs-5 col-lg-5 alert alert-dismissible alert-danger study_style">
                            {% for j in project%}
                                {%if i.user_id == j.user_id %}
                                    <h5> <a href="{% url "home:project_detail" j.id %}">{{j.title}}</a></h5>
                                {% endif %}
                            {% endfor %}
                            <h4>{{i}}</h4>
                        </div>
                    {% endfor %}
                </div>
                <a href="{% url "study:study_makeproject" study.id %}" class="btn btn-primary btn-sm">makePROJCET</a>

                <hr/>
                <h2>공동목표todo-list</h2>
                <ul>
                    {% for todo in study.grouptodo_set.all %}
                        <li>
                            <h6>{{ todo.todo }}</h6>
                            <small> {{ todo.completed}}</small>
                            <small>at {{ todo.create_at}}</small>
                            <small>at {{ todo.updated_at }}</small>
                        </li>
                    {% endfor %}
                </ul>
                <hr/>
                <h2>스터디모임 게시판</h2>
                <ul>
                    {% for post in study.post_set.all%}
                        <li>
                            {{ post.id }}
                            <a href="/study/{{ post.id }}">
                                {{ post.title }}
                            </a>
                        </li>
                        <small>{{ post.user}}</small>
                        <small>{{ post.updated_at }}</small>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>


{%  endblock %}

highlighter/study/templates/study/study_list.html
{% extends "homee/layout.html" %}
{% load imagekit %}
{% load bootstrap3 %}
{% block content %}
    <div class="jumbotron">
        <h1>HighLighter Project <sup>by coldcrust</sup></h1>
        <p>여러분의 자기관리 페이스메이커가 되어드리겠습니다.</p>
        <h2>
            <a class="btn btn-lg btn-primary" href="{% url "home:project_rcmd" %}">
                내 스터디 추천받기^^
            </a>
        </h2>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <h3>Study목록</h3>
            <table class="table table-hover table-bordered">
                <tbody>
                {% for study in study_list%}
                    <tr>
                        <div class="col-sm-6 col-md-2 sizess">
                            <div class="thumbnail">
                                <a href="/study/{{ study.id }}">
                                    {% if project.photo %}
                                        {% thumbnail "200x100" study.photo -- style="" onclick="" class=""%}
                                    {%  endif %}
                                </a>
                                <h6>
                                    <div class="mul_tum_data">
                                        <a href="/study/{{ study.id }}">
                                            {{ study.title }}
                                        </a>
                                    </div>
                                </h6>
                                <h6><a>{{ study.user }}</a></h6>
                                <h6>{{ study.created_at }}</h6>
                            </div>
                        </div>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

highlighter/study/templates/study/study_makeproject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table>
    <form action="" method="post">
        {%  csrf_token %}

        <table>
            {{ form.as_table }}
        </table>
        <input type="submit"/>
    </form>
</table>
</body>
</html>