highlighter/highlighter/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect



urlpatterns = [
    url(r'^$', lambda r:redirect('home:project_list'), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^homee/',include('home.urls',namespace='home')),
    url(r'^study/',include('study.urls',namespace='study')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/',include(debug_toolbar.urls)),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

highlighter/home/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^new/$',views.project_new,name="project_new"),
    url(r'^(?P<id>\d+)/edit/$',views.project_edit),
    url(r'^search/$',views.project_search, name='project_search'),
    url(r'^$',views.project_list, name='project_list'),
    url(r'^(?P<id>\d+)/$',views.project_detail, name='project_detail'),
    url(r'^(?P<id>\d+)/like$',views.project_like, name='project_like'),
    url(r'^rcmd/$',views.project_rcmd, name='project_rcmd'),
]

highlighter/study/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.study_list, name='study_list'),
    url(r'^(?P<id>\d+)/$',views.study_detail),
    url(r'^(?P<id>\d+)/participate$', views.study_participate, name='study_participate'),
    url(r'^(?P<id>\d+)/makeproject$', views.study_makeproject, name='study_makeproject'),
]

highlighter/highlighter/templates/highlighter/layout.html
{%  load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0,maximum-scale=1.0, user-scalable=no" />
    <title>{% block title %}HighLighter{% endblock %}</title>
    <!-- 기본 bootstrap -->
    {# <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" /> #}
    {# <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" /> #}
    {% comment %}<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/journal/bootstrap.min.css" />{% endcomment %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/journal/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static "home/style.css"%}" />

    {% block extra_head %}{% endblock %}
    <!-- bootstrap: cosmo theme -->
    <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css" /> -->

    {#    <link rel="stylesheet" href="/static/style.css" />#}
    {#    <link rel="stylesheet" href="{% static style.css %}" />#}

</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid nav-search">
        <div class="navbar-header col-xs-1 col-sm-1 col-md-2">
{#            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#            </button>#}
            <a class="logo_text" href="{% url "root" %}">H</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <div class="col-xs-6 col-sm-6 col-md-6 form-horizontal ">

                <div class="col-md-12 magin-top">
                    <form class="form-group" action="search/" method="get">
                        <div class="has-error">
                            <div class="col-xs-10 col-md-9 input_size">
                                <input type="text" class="form-control input-sm" placeholder="Elasticsearch를 이용한 전문검색" name="keyword" value="{{ fq }}" />
                            </div>
                            <div class="col-sm-2 col-md-2 button_size">
                                <button type="submit" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon glyphicon-zoom-in"></span></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-xs-5 col-sm-5 col-md-4 cus_nav_right">
                <ul class="nav nav-pills navbar-right cus_font ">
                    {% if not user.is_authenticated %}
                        <li><a href=#>스터디생성</a></li>
                        <li><a class="nav-link active" href="{% url "signup" %}" class="text-danger">회원가입</a></li>
                        {#                        next is current page and request. is context_processor#}
                        <li><a href="{% url "login" %}">로그인</a></li>
                    {% else %}
                        <li><a href=#>스터디생성</a></li>
                        <li><a href="{% url "home:project_new" %}">새글쓰기</a></li>
                        <li><a href="{% url "profile" %}">대쉬보드</a></li>
                        <li><a href="{% url "logout" %}?next={{ request.path }}">로그아웃</a></li>
                    {% endif %}
                </ul>
            </div>

        </div>
    </div>
    {#    </div>#}
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 col-lg-2 sidebar">
            <ul class="nav nav-sidebar">
                <li>
                    <a href="{% url "root" %}">HOME</a>
                </li>
            </ul>
            <ul class="nav nav-sidebar">
                <li>
                    <a href="#">PROJECT</a>
                </li>
            </ul>
            <ul class="nav nav-sidebar">
                <li>
                    <a href="{% url "study:study_list" %}">STUDY</a>
                </li>
            </ul>
            <hr/>
            <ul class="nav nav-sidebar">
                <li>
                    <a >
                        인기프로젝트
                    </a>
                </li>
                <a href="" ><li>토익 900점 도전 프로젝트</li></a>
                <li> 추성훈처럼 몸짱 도전</li>
                <li>월 30만원씩 적금</li>
                <div class="collapse" id="collapsePro">
                    <li><a>낑깡</a></li>
                    <li><a>낑깡</a></li>
                    <li><a>낑깡</a></li>
                </div>
                <li><a href="#collapsePro" data-toggle="collapse" aria-expanded="false" aria-controls="collapsePro">더보기<span class="caret"></span></a></li>
            </ul>
            <hr/>
            <ul class="nav nav-sidebar">
                <li>
                    <a>
                        인기스터디
                    </a>
                </li>
                <li>tofle 900</li>
                <a href="" ><li>9급 공무원 합격 기원 스터디</li></a>
                <li>7급 공무원 합격 기원 스터디</li>
                <div class="collapse" id="collapseStu">
                    <li><a>낑</a></li>
                    <li><a>낑</a></li>
                    <li><a>낑</a></li>
                </div>
                <li><a href="#collapseStu" data-toggle="collapse" aria-expanded="false" aria-controls="collapseStu">더보기<span class="caret"></span></a></li>
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% if messages %}
                <div class="alert alert-{{ message.tags }}">
                    {% for message in messages %}
                        {{  message.tags }} {#  메세지level #}
                        {{  message.message }}{#  실제메세 지내용 #}
                    {% endfor %}
                </div>
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>

        {#        <div id="page-footer">#}
        {#            <div class="container navbar-fixed-bottom">#}
        {#                <p class="text-muted">#}
        {#                    &copy; ColdCrust#}
        {#                    피자한판드세요#}
        {#                </p>#}
        {#            </div>#}
        {#        </div>#}
    </div>
</div>





{#    <div class="container">#}
{#        <div class="alert alert-info">#}
{##}
{#        </div>#}
{##}
{#        <div class="alert alert-success">#}
{##}
{#        </div>#}
{##}
{#        <div class="alert alert-danger">#}
{##}
{#        </div>#}
{##}
{#        <div class="alert alert-warning">#}
{##}
{#        </div>#}
{#    </div>#}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script>
    $(function () {
        $(document).ready(function () {
            $('#addItem').on('click', addItem);
            $('#todos').on('change', '.completeItem', completeItem);
            $('#todos').on('click', '.checkItem', checkItem);
            $('#todos').on('click', '.deleteItem', deleteItem);
            $('#todos').on('click', '.todoText', startEditing);
            $('#todos').on('click', '.saveItem', stopEditing);
            $('#newTodo').on('keypress', function (event) {
                if (event.which === 13) {
                    addItem();
                    event.preventDefault();
                }
            });

            function startEditing(event) {
                var taskLi = $(this).parent();
                var currentText = taskLi.find('.todoText').text();
                taskLi.find('.editText').val(currentText);
                taskLi.find('.editText').show();
                taskLi.find('.saveItem').show();
                taskLi.find('.todoText').hide();
            }

            function stopEditing(event) {
                $(this).hide();
                var taskLi = $(this).parent();
                var newValue = taskLi.find('.editText').val();
                taskLi.find('.editText').hide();
                taskLi.find('.todoText').text(newValue);
                taskLi.find('.todoText').show();
            }

            function addItem(event) {
                var newTodoText = $('#newTodo').val();
                if (newTodoText === "")
                    alert("할일을 입력하시오!");
                else
                    $('#todos').append('<li><input class="completeItem" type="checkbox"><span class="todoText"> ' + newTodoText +
                        '</span><input type="text" class="editText"><button class="btn btn-success saveItem">save</button>' +
                        '<span class="glyphicon glyphicon-trash deleteItem"></span></li>');
                $('#newTodo').val("");
            }

            function deleteItem(event) {
                event.preventDefault();
                $(this).parent().remove();
            }

            function checkItem(event) {
                event.preventDefault();
                $(this).parent().toggleClass('done');
            }

            function completeItem(event) {
                event.preventDefault();
                $(this).parent().toggleClass('done');
                $(this).parent().find('.checkItem').hide();
            }
        })
    });
</script>
<{% block extra_body %}
{%  endblock %}
</body>
</html>